#!/bin/bash

echo none | sudo tee /sys/class/leds/beaglebone\:green\:usr0/trigger > /dev/null
echo none | sudo tee /sys/class/leds/beaglebone\:green\:usr1/trigger > /dev/null
echo none | sudo tee /sys/class/leds/beaglebone\:green\:usr2/trigger > /dev/null
echo none | sudo tee /sys/class/leds/beaglebone\:green\:usr3/trigger > /dev/null
