#!/bin/bash

# Functions to check Internet connectivity
# Command line argument : internet

source textformatting

function checkInternet() {
  wget -q --tries=10 --timeout=20 --spider http://google.com
  if [[ $? -eq 0 ]]; then
    echo $greenfg "Internet connection is active" $resetall
    return 0
  else
    echo $redfg$whitebg "No Internet connection" $resetall
    return 1
  fi
}

if [[ $(uppercase $1) == "INTERNET" ]]; then
  checkInternet
fi
