#!/bin/bash

# Functions to install nodejs
# Command line argument : install

source textformatting

function installMongoDb() {
  echo $cyanfg "Need to run apt-get update" $resetall
  sudo apt-get update && sudo apt-get dist-upgrade -y

  sudo apt-get install -y build-essential libssl-dev git scons libboost-filesystem-dev libboost-program-options-dev libboost-system-dev libboost-thread-dev

  cd ~/
  mkdir projects
  cd projects

  echo $cyanfg "Cloning mongo db source" $resetall
  git clone git://github.com/mongodb/mongo.git
  cd mongo
  git checkout r3.0.7

  mv src/third_party/v8-3.25/SConscript  src/third_party/v8-3.25/SConscript.old

  cp ~/scripts/SConscript ~/projects/mongo/src/third_party/v8-3.25/SConscript

  echo $cyanfg "Build and install mongodb" $resetall

  scons --ssl --wiredtiger=off --js-engine=v8-3.25 --c++11=off --disable-warnings-as-errors CXXFLAGS="-std=gnu++11" core

  scons --ssl --wiredtiger=off --js-engine=v8-3.25 --c++11=off --disable-warnings-as-errors CXXFLAGS="-std=gnu++11" --prefix=/home/ubuntu/bin/mongodb install
}

if [[ $(uppercase $1) == "INSTALL" ]]; then
  installMongoDb
fi

if [[ $(uppercase $1) == "UNINSTALL" ]]; then
#  sudo service mongod stop
#  sudo apt-get purge mongodb-org*
#  sudo rm -r /var/log/mongodb
#  sudo rm -r /var/lib/mongodb
fi

if [[ $(uppercase $1) == "START" ]]; then
  ~/bin/mongod --dbpath /home/ubuntu/data/db --logpath /home/ubuntu/data/log/mongodb.log --fork
fi

if [[ $(uppercase $1) == "STOP" ]]; then
  sudo service mongod stop
fi

if [[ $(uppercase $1) == "RESTART" ]]; then
  sudo service mongod restart
fi

if [[ $(uppercase $1) == "LOG" ]]; then
#  set -x
#  cat /var/log/mongodb/mongod.log
#  set +x
#
  cat ~/data/log/mongodb.log

fi
